SELECT T.ANIMAL_ID AS ANIMAL_ID, T.NAME AS NAME
FROM
(
SELECT DATEDIFF (O.DATETIME, I.DATETIME) AS Period, I.ANIMAL_ID AS ANIMAL_ID, I.NAME AS NAME
FROM ANIMAL_INS I
INNER JOIN ANIMAL_OUTS O
ON I.ANIMAL_ID = O.ANIMAL_ID
ORDER BY Period DESC
) T
LIMIT 2
