
SELECT U.USER_ID AS USER_ID, U.NICKNAME AS NICKNAME, B.TOTAL_SALES AS TOTAL_SALES
FROM USED_GOODS_USER U
INNER JOIN
(
SELECT WRITER_ID, SUM(PRICE) TOTAL_SALES
FROM USED_GOODS_BOARD B
WHERE B.STATUS = 'DONE'
GROUP BY WRITER_ID
HAVING SUM(PRICE) >= 700000
) B
ON U.USER_ID = B.WRITER_ID
ORDER BY B.TOTAL_SALES ASC